{
    'name' : 'ultima',
    'version' : '1.0',
    'summary': 'Ultima website module',
    'sequence': 200,
    'description': """Developed by Xsellence Bangladesh Limited.""",
    'category': '',
    'website': '',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'data/ashik/custom_sequence.xml',
        'views/ashik/views.xml',
        'views/razzak/views.xml',
        'views/root_menu/root_menu.xml',
        'views/ashik/views_menu.xml',
        'views/razzak/views_menu.xml',

        # Templates
        'templates/base_templates/base_layout.xml',
        'templates/ashik/contact_us.xml',
        'templates/ashik/AMC_service.xml',
        'templates/ashik/service_request.xml',
        'templates/ashik/about_us.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'assets': {},
    'license': 'LGPL-3',
}
